---

- name: Download blockchain data
  get_url:
    url: "{{ neogo__db_dump_url }}"
    dest: "{{ neogo__db_dump_name }}"
  when: (neogo__db_dump_url is defined) and (neogo__db_dump_url|length > 0)

- name: Copy blockchain DB dump
  copy:
    src: "{{ neogo__db_dump_name }}"
    dest: "{{ neogo__data_dir }}"
    owner: "{{ neogo__user }}"
    group: "{{ neogo__group }}"
  register: db_changed_flag

- name: Stop the Service
  systemd:
    name: "neo-go-{{ neogo__network }}.service"
    state: "stopped"

- name: Remove obsolete DB if exists
  file:
    path: "{{ neogo__data_dir }}/{{ neogo__network }}.bolt"
    state: absent

- name: Restore DB from dump
  command: |
      neo-go db restore
      --{{ neogo__network }}
      --config-path={{ neogo__conf_dir }}
      --in {{ neogo__data_dir }}/{{ neogo__db_dump_name }}

- name: Set an owner for DB file
  file:
    path: "{{ neogo__data_dir }}/{{ neogo__network }}.bolt"
    state: file
    owner: "{{ neogo__user }}"
    group: "{{ neogo__group }}"
