---

- name: Ensure docker-compose directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ neogo__compose_path }}/{{ neogo__instance }}"

- name: Copy docker-compose file
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ neogo__compose_path }}/{{ neogo__instance }}/docker-compose.yml"

- name: Copy systemd unit file
  ansible.builtin.template:
    src: "neogo.service.compose.j2"
    dest: "/etc/systemd/system/neo-go{{ neogo__instance }}.service"
