---

# Maybe it would be better to store it in a local cache and then copy to remote
# TODO: Make sure it will download a new version even if old binary is already there
- name: Download Neo Go binary
  ansible.builtin.uri:
    method: GET
    dest: "{{ neogo__bin_path }}"
    url: "{{ neogo__release_url }}"
    validate_certs: no
    status_code: 201,304
  when: neogo__download_fresh_binary == true

- name: Copy systemd unit file
  ansible.builtin.template:
    src: "neo-go.service.j2"
    dest: "/etc/systemd/system/neo-go{{ neogo__instance }}.service"
