---

# Maybe it would be better to store it in a local cache and then copy to remote
# TODO: Make sure it will download a new version even if old binary is already there
- name: Download Neo Go binary
  uri:
    method: GET
    dest: "{{ neo_go_bin_path }}"
    url: "{{ neo_go_release_url }}"
    validate_certs: no
    status_code: 201,304
  when: neo_go_download_fresh_binary == true

- name: Copy systemd unit file
  template:
    src: "neo-go.service.j2"
    dest: "/etc/systemd/system/neo-go-{{ neo_go_network }}.service"
