---

- name: Ensure there is neo-go group
  ansible.builtin.group:
    name: "{{ neogo__group }}"
    system: yes

- name: Ensure there is neo-go user
  ansible.builtin.user:
    name: "{{ neogo__user }}"
    password: !
    shell: /usr/sbin/nologin
    home: "{{ neogo__data_dir }}"
    system: yes
    group: "{{ neogo__group }}"

- name: Get uid for neo-go user
  ansible.builtin.getent:
    database: passwd
    key: "{{ neogo__user }}"

- name: Get gid for neo-go user
  ansible.builtin.getent:
    database: group
    key: "{{ neogo__group }}"
